### ISSUE TITLE
[4.4:69] The system shall support inline rendering of notes right after the note reference…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#50]
### Requirement

[[4.4:69]](http://snaekobbi.github.io/requirements#4.4:69) The system shall support inline rendering of notes right after the note reference, possibly surrounded by brackets or the like. This feature shall be supported at least for very small notes. As an option, notes may be floated to the end of sentences.
### Tasks
- [ ] CSS specification (@bertfrees)
- [x] implementation (@bertfrees)
- [ ] system tests
  - [x] @stesk ![FAIL](http://snaekobbi.github.io/sprints/FAIL.svg)
### Test results
- DK: I tried to achieve this in CSS by setting `display: inline` on `noteref::alternate`. This seems to fail, probably because note elements contain paragraphs (and, in one case, mixed content).

**Comment by bertfrees** [comment]
This has been implemented but not documented. For more information about how to use this ask me.

**Comment by bertfrees** [comment]
@stesk: what exactly went wrong here? Is it just a matter of setting `note p { display: inline }`? Or did the notes not show up at all?

**Comment by stesk** [comment]
@bertfrees I put `display: inline` on `noteref::alternate`, which didn't (and possibly shouldn't?) work. It's not one of "our" features, so I only did one very quick test. Maybe I can retest at a later point with the rule you suggest.

**Comment by bertfrees** [comment]
I was going to add a little test for inline notes to pipeline-mod-nlb but if it's not one of "your" features maybe it's no use. `display:inline` on `noteref::alternate` makes the `<note>` element into an inline box but not the `<p>` inside.
