### ISSUE TITLE
[4.9:114] The system shall provide the user with help and guidance for creating templates.

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#94]
### Requirement

[[4.9:114]](http://snaekobbi.github.io/requirements#4.9:114) The system shall provide the user with help and guidance for creating templates.
### Tasks
- [x] user guide for creating templates: https://github.com/daisy/pipeline-webui/wiki/Templating (@josteinaj)
- [ ] script documentation (options etc.)

**Comment by josteinaj** [comment]
Is this just a matter of documenting the templating feature, or does it mean we need some sort of wizard or something?

**Comment by bertfrees** [comment]
I sincerely hope we don't need to make wizards. I think documentation is a very good start, yes. As long as the job creation page (options etc.) is well documented we can get far. For example, being able to have links from options to detailed documentation (see https://github.com/daisy/pipeline-webui/issues/32).

**Comment by josteinaj** [comment]
As described in daisy/pipeline-webui#32, this requires a change in the web api, right?

**Comment by bertfrees** [comment]
I think so, yes.
