### ISSUE TITLE
[4.7:118] The system shall support the creation of symbols lists, when characters have different meaning than normally…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#98]
### Requirement

[[4.7:118]](http://snaekobbi.github.io/requirements#4.7:118) The system shall support the creation of symbols lists, when characters have different meaning than normally (e.g. in mathematics).
### Done

We have an idea about how to implement.
## sprint#9
- [x] ~~implement: [[pipeline-mod-dedicon#28] Symbols list](https://github.com/snaekobbi/pipeline-mod-dedicon/issues/28) (@dkager)~~ (**cancelled**)

**Comment by dkager** [comment]
Note that my idea for implementation is quite tailored to Dedicon. It uses an external XML file with the symbols and their replacements.

**Comment by bertfrees** [comment]
That's perfectly fine. If the XML can be made part of the system, that would be preferred, but alternatively it could be passed as an input (and stored in a template).

**Comment by dkager** [comment]
The symbols definitions themselves should preferrably be external, because the list is used in other systems too.

**Comment by bertfrees** [comment]
It could be a software component that you can used in multiple systems. Or you can build one component for each system from the same source code.

**Comment by dkager** [comment]
Yes, but there has to be added value.
